# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('info_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='StationCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_code', models.CharField(max_length=32)),
                ('checkin', models.DateTimeField(verbose_name='checkin')),
                ('checkout', models.DateTimeField(verbose_name='chekout')),
                ('checkedin_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkedin_by', to=settings.AUTH_USER_MODEL)),
                ('checkedout_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkedout_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('max_points', models.PositiveIntegerField()),
                ('show_on_details', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kimball.StationComponent')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Station')),
            ],
        ),
        migrations.CreateModel(
            name='StationComponentTeamPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(max_length=500)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.StationCheckpoint')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.StationComponent')),
            ],
        ),
        migrations.CreateModel(
            name='StationStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_number', models.PositiveIntegerField()),
                ('group_name', models.CharField(max_length=200)),
                ('checkin_code', models.CharField(max_length=32)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nin', models.CharField(max_length=13)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timebox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('info_url', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Edition')),
            ],
        ),
        migrations.AddField(
            model_name='stationcheckpoint',
            name='patrol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Team'),
        ),
        migrations.AddField(
            model_name='stationcheckpoint',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Station'),
        ),
        migrations.AddField(
            model_name='station',
            name='timebox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kimball.Timebox'),
        ),
    ]
