# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='nin',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
