# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0002_auto_20171121_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
