# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kimball', '0003_auto_20171123_1751'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationstaff',
            unique_together=set([('station', 'user')]),
        ),
    ]
