# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0004_auto_20171123_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationcheckpoint',
            name='checkedout_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkedout_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stationcheckpoint',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='chekout'),
        ),
    ]
