# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0005_auto_20171123_1809'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationcomponentteampoints',
            unique_together=set([('component', 'checkpoint')]),
        ),
    ]
