# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0007_auto_20171124_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationcomponentteampoints',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
