# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0008_auto_20171124_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationcheckpoint',
            name='checkin_code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
