# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0009_auto_20171128_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='stationcomponent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='kimball.StationComponent'),
        ),
        migrations.AddField(
            model_name='stationcomponent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kimball.ComponentGroup'),
        ),
    ]
