# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0010_auto_20180117_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationcomponent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kimball.StationComponent'),
        ),
    ]
