# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0011_auto_20180117_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='locale',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
