# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0012_team_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='locale',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
