# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimball', '0013_auto_20180124_1921'),
    ]

    ddl_reverse = "DROP VIEW IF EXISTS kimball_scoreboard_v;"

    ddl = """
        CREATE VIEW kimball_scoreboard_v AS 
        SELECT 
            0 AS id,
            t.id AS team_id, 
            COALESCE(SUM(p.points),0) AS points 
        FROM kimball_stationcomponentteampoints p 
        INNER JOIN kimball_stationcheckpoint cp ON p.checkpoint_id = cp.id
        INNER JOIN kimball_stationcomponent sc ON p.component_id = sc.id
        INNER JOIN kimball_team t ON cp.patrol_id = t.id
        WHERE cp.checkout IS NOT NULL
        AND sc.parent_id IS NULL 
        GROUP BY t.id
        ORDER BY points DESC;
        """

    operations = [
        migrations.RunSQL(ddl, ddl_reverse),
    ]
